name: deployments

on:
  push:
    branches:
      - main
      - dell-staging
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancel active outdated workflows when a newer workflow is running for the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-deploy-staging:
    name: Deploy Frontend (Staging)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Get Vercel project_id
        id: get_project_id
        run: echo "::set-output name=id::$(github.ref)"

      - name: Output project_id
        run: echo ${{ steps.get_project_id.outputs.id }}

      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Deploy frontend to Vercel staging instance
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ matrix.proj_id }}
      #     scope: ${{ secrets.VERCEL_TEAM_ID }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     vercel-args: "--prod"
